# dev_appserver.py --port=8080 app.yaml

# Change this in prod
runtime: go119  

handlers:
  - url: /static
    static_dir: static
  
  - url: /api/.* 
    script: auto 

  - url: /service-worker.js
    static_files: static/js/service-worker.js
    upload: static/js/service-worker.js

  - url: /.*
    static_files: static/index.html
    upload: static/index.html

