# dev_appserver.py --port=8080 app.yaml

runtime: go119  

handlers:
  - url: /static
    static_dir: static
  
  - url: /api/.* 
    script: auto 

  - url: /service-worker.js
    static_files: static/js/service-worker.js
    upload: static/js/service-worker.js

  - url: /manifest.json
    static_files: static/manifest.json
    upload: static/manifest.json

  - url: /home.*
    static_files: static/index.html
    upload: static/index.html

  - url: /.*
    script: auto

